CREATE TABLE znodata( year INT, outid CHAR(300), birth BIGINT, sextypename CHAR(300), regname CHAR(300),
					 areaname CHAR(300), tername CHAR(300), regtypename CHAR(300), tertypename CHAR(300),
					 classprofilename CHAR(300), classlangname CHAR(300), eoname CHAR(300), eotypename CHAR(300),
					 eoregname CHAR(300), eoareaname CHAR(300), eotername CHAR(300), eoparent CHAR(300),
					 umltest CHAR(300), umlteststatus CHAR(300), umlball100 REAL, umlball12 REAL, umlball REAL,
					 umladaptscale REAL, umlptname CHAR(300), umlptregname CHAR(300), umlptareaname CHAR(300),
					 umlpttername CHAR(300), ukrtest CHAR(300), ukrsubtest CHAR(300), ukrteststatus CHAR(300),
					 ukrball100 REAL, ukrball12 REAL, ukrball REAL, ukradaptscale REAL, ukrptname CHAR(300),
					 ukrptregname CHAR(300), ukrptareaname CHAR(300), ukrpttername CHAR(300), histtest CHAR(300),
					 histlang CHAR(300), histteststatus CHAR(300), histball100 REAL, histball12 REAL, histball REAL,
					 histptname CHAR(300), histptregname CHAR(300), histptareaname CHAR(300), histpttername CHAR(300),
					 mathtest CHAR(300), mathlang CHAR(300), mathteststatus CHAR(300), mathball100 REAL,
					 mathball12 REAL, mathdpalevel CHAR(300), mathball REAL, mathptname CHAR(300),
					 mathptregname CHAR(300), mathptareaname CHAR(300), mathpttername CHAR(300),
					 mathsttest CHAR(300), mathstlang CHAR(300), mathstteststatus CHAR(300), mathstball12 REAL,
					 mathstball REAL, mathstptname CHAR(300), mathstptregname CHAR(300), mathstptareaname CHAR(300),
					 mathstpttername CHAR(300), phystest CHAR(300), physlang CHAR(300), physteststatus CHAR(300),
					 physball100 REAL, physball12 REAL, physball REAL, physptname CHAR(300), physptregname CHAR(300),
					 physptareaname CHAR(300), physpttername CHAR(300), chemtest CHAR(300), chemlang CHAR(300),
					 chemteststatus CHAR(300), chemball100 REAL, chemball12 REAL, chemball REAL, chemptname CHAR(300),
					 chemptregname CHAR(300), chemptareaname CHAR(300), chempttername CHAR(300), biotest CHAR(300),
					 biolang CHAR(300), bioteststatus CHAR(300), bioball100 REAL, bioball12 REAL, bioball REAL,
					 bioptname CHAR(300), bioptregname CHAR(300), bioptareaname CHAR(300), biopttername CHAR(300),
					 geotest CHAR(300), geolang CHAR(300), geoteststatus CHAR(300), geoball100 REAL, geoball12 REAL,
					 geoball REAL, geoptname CHAR(300), geoptregname CHAR(300), geoptareaname CHAR(300),
					 geopttername CHAR(300), engtest CHAR(300), engteststatus CHAR(300), engball100 REAL,
					 engball12 REAL, engdpalevel CHAR(300), engball REAL, engptname CHAR(300), engptregname CHAR(300),
					 engptareaname CHAR(300), engpttername CHAR(300), fratest CHAR(300), frateststatus CHAR(300),
					 fraball100 REAL, fraball12 REAL, fradpalevel CHAR(300), fraball REAL, fraptname CHAR(300),
					 fraptregname CHAR(300), fraptareaname CHAR(300), frapttername CHAR(300), deutest CHAR(300),
					 deuteststatus CHAR(300), deuball100 REAL, deuball12 REAL, deudpalevel CHAR(300), deuball REAL,
					 deuptname CHAR(300), deuptregname CHAR(300), deuptareaname CHAR(300), deupttername CHAR(300),
					 spatest CHAR(300), spateststatus CHAR(300), spaball100 REAL, spaball12 REAL, spadpalevel CHAR(300),
					 spaball REAL, spaptname CHAR(300), spaptregname CHAR(300), spaptareaname CHAR(300),
					 spapttername CHAR(300), PRIMARY KEY (outid));

INSERT INTO znodata (year, outid, birth, sextypename, regname, areaname, tername, regtypename, tertypename,
					 classprofilename, classlangname, eoname, eotypename, eoregname, eoareaname, eotername,
					 eoparent, umltest, umlteststatus, umlball100, umlball12, umlball, umladaptscale, umlptname,
					 umlptregname, umlptareaname, umlpttername, ukrtest, ukrsubtest, ukrteststatus, ukrball100,
					 ukrball12, ukrball, ukradaptscale, ukrptname, ukrptregname, ukrptareaname, ukrpttername,
					 histtest, histlang, histteststatus, histball100, histball12, histball, histptname, histptregname,
					 histptareaname, histpttername, mathtest, mathlang, mathteststatus, mathball100, mathball12,
					 mathdpalevel, mathball, mathptname, mathptregname, mathptareaname, mathpttername, mathsttest,
					 mathstlang, mathstteststatus, mathstball12, mathstball, mathstptname, mathstptregname,
					 mathstptareaname, mathstpttername, phystest, physlang, physteststatus, physball100, physball12,
					 physball, physptname, physptregname, physptareaname, physpttername, chemtest, chemlang,
					 chemteststatus, chemball100, chemball12, chemball, chemptname, chemptregname, chemptareaname,
					 chempttername, biotest, biolang, bioteststatus, bioball100, bioball12, bioball, bioptname,
					 bioptregname, bioptareaname, biopttername, geotest, geolang, geoteststatus, geoball100,
					 geoball12, geoball, geoptname, geoptregname, geoptareaname, geopttername, engtest,
					 engteststatus, engball100, engball12, engdpalevel, engball, engptname, engptregname,
					 engptareaname, engpttername, fratest, frateststatus, fraball100, fraball12, fradpalevel,
					 fraball, fraptname, fraptregname, fraptareaname, frapttername, deutest, deuteststatus,
					 deuball100, deuball12, deudpalevel, deuball, deuptname, deuptregname, deuptareaname,
					 deupttername, spatest, spateststatus, spaball100, spaball12, spadpalevel, spaball, spaptname,
					 spaptregname, spaptareaname, spapttername)
					 VALUES (2021, '8a2abef7-625a-4253-8c14-000fe8a856e5', 2003, 'чоловіча',
 'Дніпропетровська область', 'м.Кам’янське', 'Дніпровський район міста',
 'Студент закладу вищої освіти', 'місто', 'Молодший спеціаліст', 'українська',
 'Кам’янський державний енергетичний технікум',
 'заклад фахової передвищої освіти', 'Дніпропетровська область',
 'м.Кам’янське. Дніпровський район міста', 'Дніпровський район міста',
 'Департамент освіти і науки Дніпропетровської облдержадміністрації',
 'Українська мова і література', 'Зараховано', 120.0, 5.0, 42.0, 0.0,
 'Комунальний заклад "Загальноосвітній навчальний заклад І ступеня- гімназія № 39 " Кам’янської міської ради',
 'Дніпропетровська область', 'м.Кам’янське. Дніпровський район міста',
 'Дніпровський район міста', 'Українська мова' ,'Так' ,'Зараховано', 124.0 , 'NaN',
 29.0, 0.0,
 'Комунальний заклад "Загальноосвітній навчальний заклад І ступеня- гімназія № 39 " Кам’янської міської ради',
 'Дніпропетровська область' ,'м.Кам’янське. Дніпровський район міста',
 'Дніпровський район міста', 'Історія України', 'українська' ,'Зараховано',
 103.0, 7.0, 28.0,
 'Комунальний заклад "Середня загальноосвітня школа № 30" Кам’янської міської ради',
 'Дніпропетровська область' ,'м.Кам’янське. Дніпровський район міста',
 'Дніпровський район міста', 'Математика', 'українська', 'Зараховано', 105.0,
 4.0, 'стандарт(академічний)',11.0,
 'Комунальний заклад "Середня загальноосвітня школа № 30" Кам’янської міської ради',
 'Дніпропетровська область' ,'м.Кам’янське. Дніпровський район міста',
 'Дніпровський район міста' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN', 'Географія', 'українська',
 'Зараховано' ,124.0, 6.0, 37.0,
 'Комунальний заклад "Середня загальноосвітня школа № 30" Кам’янської міської ради',
 'Дніпропетровська область', 'м.Кам’янське. Дніпровський район міста',
 'Дніпровський район міста' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'),
 (2021, '3e975d01-9cc9-4072-bbcd-005b9da75096', 2003, 'чоловіча',
 'Кіровоградська область', 'м.Кропивницький', 'Фортечний район міста',
 'Випускник загальноосвітнього навчального закладу 2021 року', 'місто',
 'Технологічний', 'українська',
 'Комунальний заклад "Ліцей "Науковий" Міської ради міста Кропивницького"',
 'ліцей', 'Кіровоградська область' ,'м.Кропивницький. Фортечний район міста',
 'Фортечний район міста',
 'Управління освіти Міської ради міста Кропивницького',
 'Українська мова і література', 'Зараховано', 143.0, 7.0, 58.0, 0.0,
 'Кіровоградський медичний фаховий коледж ім. Є.Й. Мухіна',
 'Кіровоградська область' ,'м.Кропивницький. Подільський район міста',
 'Подільський район міста', 'Українська мова', 'Так', 'Зараховано' ,151.0 , 'NaN',
 42.0, 0.0, 'Кіровоградський медичний фаховий коледж ім. Є.Й. Мухіна',
 'Кіровоградська область' ,'м.Кропивницький. Подільський район міста',
 'Подільський район міста' ,'Історія України', 'українська', 'Зараховано',
 145.0 ,9.0, 44.0,
 'Центральноукраїнський інститут Приватного Акціонерного Товариства "Вищий навчальний заклад "Міжрегіональна Академія управління персоналом"',
 'Кіровоградська область', 'м.Кропивницький. Подільський район міста',
 'Подільський район міста', 'Математика' ,'українська', 'Не подолав поріг',
 0.0 ,3.0, 'стандарт(академічний)', 9.0,
 'Кіровоградський медичний фаховий коледж ім. Є.Й. Мухіна',
 'Кіровоградська область' ,'м.Кропивницький. Подільський район міста',
 'Подільський район міста' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' ,'Фізика',
 'українська' ,'Зараховано', 120.0, 5.0, 18.0,
 'Комунальний заклад "Навчально-виховний комплекс "Спеціалізований загальноосвітній навчальний заклад І-ІІІ ступенів № 26 - дошкільний навчальний заклад-дитячий юнацький центр "Зорецвіт" Кіровоградської міської ради Кіровоградської області',
 'Кіровоградська область', 'м.Кропивницький. Подільський район міста',
 'Подільський район міста' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN' , 'NaN'
 , 'NaN' , 'NaN' , 'NaN' , 'NaN');